### ISSUE TITLE
DNS check stuck

### ISSUE THREAD

**Issue by ghost** [DNS-OARC/services#18]
the https://cmdns.dev.dns-oarc.net/ always stuck at remaining 3 lookups.

Enabled DNS server: Uncensored DNS Unicast DoH.

89.233.43.71 
2a01:3a0:53:53::
https://unicast.uncensoreddns.org/dns-query

Thank you.

![D846F9ED-45E4-4B6F-A835-234A2D31F25A](https://user-images.githubusercontent.com/76554148/105861044-944f1d00-5fee-11eb-9e8f-8c69583e717a.jpeg)

**Comment by jelu** [comment]
How long is `always stuck`?

That looks like an iPad, what browser is it? It might be browser related.

**Comment by ghost** [comment]
stuck as stops and nothing happens. 1/2 hour gone just now.

It's an iPad with iPadOS 14.3 and Safari and I'm claiming because the previous version with Beta sticker worked fine in the same configuration.

https://blog.uncensoreddns.org/dns-servers/

**Comment by jelu** [comment]
But how long did you wait?

And can you try another browser on your iPad?

**Comment by jelu** [comment]
Please try another browser, I mainly develop using Firefox but I have check that this works on Brave also, both Android and iOS.

**Comment by ghost** [comment]
> But how long did you wait?

as mentioned, 1/2 hour

> And can you try another browser on your iPad?

I can, but the Beta worked fine with Safari...

**Comment by jelu** [comment]
That "Beta" is no more, this is the new version. Please try other browsers so we can know if its a Safari issue or not.

**Comment by ghost** [comment]
Its not a Safari issue. The test page stops responding when DoH or DoT is enabled.

**Comment by jelu** [comment]
So what other browser did you test with?

**Comment by jelu** [comment]
Or do you mean you disabled DoH in Safari and it worked?

**Comment by ghost** [comment]
> Or do you mean you disabled DoH in Safari and it worked?

On the same DNS server the test page works if plaintext mode enabled, stop responding when DoT or DoH enabled.

**Comment by jelu** [comment]
Have you tested with other DoH services?

If not, can you test?

**Comment by ghost** [comment]
Strange, now I cant use DoH or DoT at all. ISP block?

**Comment by jelu** [comment]
There is no blocking on Check My DNS.

**Comment by ghost** [comment]
I mean, could be possible that my ISP is blocking those crypted protocols?

**Comment by jelu** [comment]
I can't help you with you're ISP, you'll need to contact them yourself.

I've tested Safari, it works. I've tested DoH with Cloudflare, NextDNS and Uncensored DNS, they all work.

So the problem is on your end.

**Comment by ghost** [comment]
Hello,
one possible reason is that a range of IP addresses of my ISP appears blacklisted on UCEPROTECTL3
Did you enabled them? I was shocked to see that they accept financial donation for delistings...

**Comment by jelu** [comment]
I have no idea what you're talking about.

There is no blocking of any kind done on our end.

**Comment by ghost** [comment]
So, the uceprotect.net is not enabled on https://cmdns.dev.dns-oarc.net/ ?

**Comment by jelu** [comment]
"no blocking of any kind"
