### ISSUE TITLE
Check My DNS: IPv6 test passes on IPv4-only network when using Quad9 as DNS

### ISSUE THREAD

**Issue by florisbrunet** [DNS-OARC/services#20]
When using Quad9's DNS server 9.9.9.9 on an IPv4-only network, the IPv6 test always succeeds. Using Google, OpenDNS, Cloudflare, NextDNS, Level3, AdGuard, Comodo, Verisign, Knot Resolver (v5.4.1) or Unbound (v1.13.2) this test will always result in a Failure on an IPv4-only network. I think this is a bug.

**Comment by jelu** [comment]
Well, yes and no.

The IPv6 transport check is checking if the resolver asks for AAAA records which is not really relevant.

I'll change the check to check whether IPv6 is used or not for the queries and I can also use the new achievements to give a IPv6 achievement if the client has IPv6 also :)

**Comment by jelu** [comment]
@debrunet Can you test on https://tcmdns.dev.dns-oarc.net/ now? I've changed the check some.

**Comment by florisbrunet** [comment]
I am still getting a Success on IPv6 for the transport test, however, the new IPv6 achievement is not awarded.

**Comment by jelu** [comment]
@debrunet Well, if the RESOLVER support IPv6 you will see a success. Check My DNS is a tester for the resolver you're using.

**Comment by florisbrunet** [comment]
Yes I understand, it seems that in this new test the other resolvers that I mentioned in the first post that support IPv6 also get a Success on the IPv6 test, where as this previously was not the case. So everything seems to work now as expected then! Awesome 😄

**Comment by jelu** [comment]
Great! I've pushed this change to cmdns. now and added tooltip description of the achievements.
