### ISSUE TITLE
[CheckMyDNS] RPKI IPv6 not detected?

### ISSUE THREAD

**Issue by bortzmeyer** [DNS-OARC/services#22]
CheckMyDNS claims that the RPKI IPv6 test failed for my resolver. Checking the IP address in the test, I find "Result Message: No RPKI origin validation between resolver and auth, or a default route is pointed to destination AS
Description: Check if RPKI origin validation is enabled between resolver and authority DNS." but the IPv6 address does have a ROA and it works (here, seen on BGPmon):

```
% This is the BGPmon.net whois Service
% You can use this whois gateway to retrieve information 
% about an IP adress or prefix
% We support both IPv4 and IPv6 address.
%
% For more information visit:
% http://bgpmon.net/bgpmonapi.php

Prefix:              2a01:e00::/26
Prefix description:  ProXad network / Free SAS
Country code:        FR
Origin AS:           12322
Origin AS Name:      PROXAD, FR
RPKI status:         ROA validation successful
First seen:          2019-11-01
Last seen:           2021-10-22
Seen by #peers:      21

```

**Comment by jelu** [comment]
It's not your networks ROA that is checked.

It checks that your network verifies ROAs to where it sends traffic.

It means that your network or your upstream actually sends traffic to a network with an invalid ROA.

**Comment by bortzmeyer** [comment]
OK, that was not clear. So, it means that Free/Proxad checks ROA for IPv4 but not for IPv6?

**Comment by bortzmeyer** [comment]
I suggest that, while the test is OK, the way it is communicated to the user could be improved.

**Comment by jelu** [comment]
> OK, that was not clear. So, it means that Free/Proxad checks ROA for IPv4 but not for IPv6?

I am not a network guy but that would be the case, or if there is an upstream somewhere doing the filtering.

> I suggest that, while the test is OK, the way it is communicated to the user could be improved.

While the UI gives very little option to explain checks in details there is an [about](https://cmdns.dev.dns-oarc.net/about.html) page which links to a blog post that explains it more.

If that is not enough maybe you can submit a text I can use on the about page?
